### ISSUE TITLE
Bug with periodic meshes

### ISSUE THREAD

**Issue by YohannDudouit** [GLVis/glvis#51] opened 2018-03-14 00:08 UTC
I don't know if this is a known bug but the cutting plane doesn't work as I would expect with periodic meshes.
![bug_glvis](https://user-images.githubusercontent.com/190171/37376353-09db16ea-26e1-11e8-99f6-468417743b40.png)

Cheers,
Y

**Comment by tzanio** [comment] 2018-03-22 19:57
Yes, that is a known issue. We'd like to address it in the future, but feel free to propose a PR :)

**Comment by v-dobrev** [comment] 2018-04-08 00:57
Since this is a real issue, let's keep it open until it is resolved.

**Comment by tzanio** [comment] 2018-10-14 23:59
Wow, that is very cool and a definite improvement (especially on coarser meshes)!

It also seems to help with #51.

**Comment by tzanio** [comment] 2018-11-02 04:11
@YohannDudouit can you try reproducing this with the new improved cutting plane algorithm? It may no longer be an issue...

**Comment by tzanio** [comment] 2018-11-29 01:41
This was likely addressed by #71.

**Closed by tzanio** 2018-11-29 01:41 UTC
Labels: bug, enhancement
