### ISSUE TITLE
Extremely slow GLVis on `ex9`

### ISSUE THREAD

**Issue by YohannDudouit** [GLVis/glvis#199] opened 2021-09-07 18:21 UTC
I recently updated my GLVis to the latest version, when "running" (after pushing "space") the time between each frame seems extremely long compared to what experienced before on MFEM `ex9` (no special option).

**Comment by tzanio** [comment] 2021-09-07 19:04
This was reproduced on macOS `10.14.6` and `10.15.7`

**Comment by YohannDudouit** [comment] 2021-09-07 19:22
After rebuilding MFEM in release mode, and rebuilding GLVis from scratch, ant then rebuilding MFEM in debug mode, the performance are much improved, though it still seems a bit slow.
Should I close this issue?

**Comment by pazner** [comment] 2021-09-07 19:42
I think it's still a regression — I don't remember ex9 being quite so slow with previous versions, even in debug mode.

**Comment by kanye-quest** [comment] 2021-09-09 16:55
This actually seems to be coming from the MFEM side. Here's the profiler view with glvis `master` but mfem 4.2:

![image](https://user-images.githubusercontent.com/21321692/132727682-d3f57d92-8ea3-4887-a67e-b119a48d2adf.png)

And here's with both glvis and mfem on `master`:

![image](https://user-images.githubusercontent.com/21321692/132727862-3d036819-78c0-4682-8964-d235efe56f7f.png)

`GetRefinedValuesAndNormals` mainly calls down into `GridFunction::GetValues` and `GridFunction::GetGradients`, however it seems that going from 4.2 to the latest release made calls to `GetValues` in particular much more expensive.

**Comment by rw-anderson** [comment] 2021-09-09 18:10
![diff](https://user-images.githubusercontent.com/11507994/132739538-31dd9e51-5432-4445-a487-4d47987ada93.png)

It looks like there was a problem introduced into GetValues. The new implementation seems to be a double nested loop over the number of integration points.

**Comment by pazner** [comment] 2021-09-09 18:22
Good find @rw-anderson! I can make a PR to fix the regression in MFEM, or you can do it if you prefer.

**Comment by rw-anderson** [comment] 2021-09-09 18:25
I have a fix running through the test suite, so I guess I can follow through and make the PR. Thanks!

**Comment by rw-anderson** [comment] 2021-09-09 18:47
I suppose someone should check to make sure this change actually resolves this particular issue, although it seems likely.

https://github.com/mfem/mfem/pull/2522

**Comment by tomstitt** [comment] 2021-09-09 18:55
I just tried https://github.com/mfem/mfem/pull/2522 with the web build and ex9 is fast again

**Comment by tzanio** [comment] 2021-09-09 23:17
@YohannDudouit, can you confirm mfem/mfem#2522 works for you?

**Comment by tzanio** [comment] 2021-09-11 22:52
Since mfem/mfem#2522 is merged in `mfem:master` now I will assume that this issue is resolved.

@YohannDudouit and @pazner -- please let me know if that's not the case and we will reopen it.

**Closed by tzanio** 2021-09-11 22:52 UTC
Labels: bug, Mac, high-impact

**Comment by pazner** [comment] 2021-09-13 01:14
> Since [mfem/mfem#2522](https://github.com/mfem/mfem/pull/2522) is merged in `mfem:master` now I will assume that this issue is resolved.
> 
> @YohannDudouit and @pazner -- please let me know if that's not the case and we will reopen it.

It's working much better for me now, thanks!
