### ISSUE TITLE
Inconsistency in command key for printing pdf files

### ISSUE THREAD

**Issue by ilonster** [GLVis/glvis#113] opened 2020-11-02 20:47 UTC
The README file say to use `Cntrl+p` in order to print pdf files, but the correct command appears to be`Shift+p` (on Mac OS-X).  The README file also explains that it is possible to print SVG and EPS formats, but does not explain how to change the output format.

**Comment by tzanio** [comment] 2020-11-02 21:19
Hi @ilonster, is this with the latest `master` of glvis?

The intention is indeed for the key to be `Ctrl+p` and that's how it works on my Mac.

`Shift+p` should circle back in the color palettes (the opposite of just `p`)...

**Comment by v-dobrev** [comment] 2020-11-02 21:24
Yes, I'm not sure why `Ctrl+p` does not work for you on macOS -- here is the code that checks for `Ctrl` modifier when `p` is pressed: https://github.com/GLVis/glvis/blob/4262972f3b190b57c578cd58db07920ab4032578/lib/vsdata.cpp#L813-L818

Regarding SVG and EPS: it looks like @tzanio wrote that comment, maybe he can clarify, but my suspision is that this may be something one can configure the `gl2ps` library (which we use to produce the pdf output) to do.

**Comment by tzanio** [comment] 2020-11-02 21:43
I will actually not recommend the `PDF` output or the `SVG` and `EPS` options of `gl2ps` which haven't been tested in a long time.

When I need an image for a talk or a paper, I just take a `PNG` screenshot with `Shift+s`.

**Comment by tzanio** [comment] 2020-11-06 01:04
@ilonster, any additional information about this issue?

**Comment by tzanio** [comment] 2020-11-20 20:10
We are not able to reproduce this, so I will close it now. If it is still an issue, please feel free to reopen/provide additional details.

**Closed by tzanio** 2020-11-20 20:10 UTC
Labels: usage
